### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [velas/mobile-wallet#219]
```
+ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/CharlesMangwa/simple-markdown.git
Directory: /home/vagrant/build/com.velas.mobile_wallet/android/app
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out
info Visit https://yarnpkg.com/en/docs/cli/install for documen
```

This looks like a network issue but I have seen this 3 times. Could you plese take a look? Thanks!

**Comment by emanuelb** [comment]
Github doesn't support `git://` protocol anymore: https://github.blog/2021-09-01-improving-git-protocol-security-github/ 
that's why `ls-remote --tags --heads git://github.com/CharlesMangwa/simple-markdown.git` fails, it should be changed to `https://` instead

**Comment by licaon-kter** [comment]
[Known issue](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10840#note_899186459) @FrozenPyrozen why wasn't this fixed already?

fyi: https://gitlab.com/fdroid/fdroiddata/-/commit/39a2ff57eeb63dc3bea16a3556419d1bb23a3da4

**Comment by FrozenPyrozen** [comment]
@licaon-kter would be fixed in https://github.com/velas/mobile-wallet/pull/240 , but for f-droid pls create build from latest commit on https://github.com/velas/mobile-wallet/pull/241 , because for now we removed `expo-camera` and `expo-barcode-sacnner` according f-droid policy, but we need them for QR scanning in our app

**Comment by licaon-kter** [comment]
@FrozenPyrozen the autoupdate process can't pickup from a branch, I'll disable the check

**Comment by licaon-kter** [comment]
@FrozenPyrozen brach has same issue:
```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/CharlesMangwa/simple-markdown.git
Directory: /home/vagrant/build/com.velas.mobile_wallet/android/app
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.114.3]: errno=Connection timed out
```

https://github.com/velas/mobile-wallet/blob/feature/VLWA-779-f-droid-publish-app-on-f-droid-market/yarn.lock#L15835

**Comment by FrozenPyrozen** [comment]
@licaon-kter try now, fixed in https://github.com/velas/mobile-wallet/pull/241/commits/8d653a1bc6b44e93423d9ad5d4c464edecf4e3c3

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/6d10e95cddaedb76295d91f8a5589b592a7e3776

@linsui close this

**Comment by linsui** [comment]
Thanks!
