### ISSUE TITLE
[Android app] Log out when filling in the '$' field in SYX wallet

### ISSUE THREAD

**Issue by den4ik89** [velas/mobile-wallet#22]
**Describe the bug**
Log out when filling in the '$' field in SYX wallet

**To Reproduce**
1. Tap wallets
2. Choose Symblox (SYX)
3. Tap 'Send'
4. Input value in the field '$'

**Actual result**
The app logs out and asks for a password

**Expected behavior**
In 'Amount' field calculates the amount of coins

**Video**
https://drive.google.com/file/d/1jzS4ssq1aW2kaa9124kFloZUC_fdcWQi/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 5 Pro
 - OS: Android 8.1.0
 - Build 1.1.0

**Comment by Corresponsible** [comment]
I can't see your application for test-session in the list, make sure you have registered here: https://forms.gle/JbyoHcGg2uLn5UdV9

**Comment by den4ik89** [comment]
> I can't see your application for test-session in the list, make sure you have registered here: https://forms.gle/JbyoHcGg2uLn5UdV9

sent information
