### ISSUE TITLE
[Android app]VLX wallet accepts ETH addresses as valid addresses

### ISSUE THREAD

**Issue by Ranger5789** [velas/mobile-wallet#24]
**Summary**
VLX wallet accepts ETH addresses as valid addresses

**Screenshots**
![Screenshot_2021-02-02-08-46-19-444](https://user-images.githubusercontent.com/10086309/106557903-ef739900-6533-11eb-83c1-04c7ed887312.jpeg)

**Steps to reproduce:**
1. Go to wallets
2. Tap VLX wallet
3. Tap 'Send'
4. Enter ETH address In 'To:' field
5. Tap 'Amount'
6. Pay attention that no error message shown

**Expected result**
Error message: Given address is not valid Velas address

**Actual result**
No error message

**Environment:**
 - Device: Lenovo TB-X606F
 - OS: Android 10
 - Version: Mobile wallet 1.1.0

**Comment by Ranger5789** [comment]
Possible not a bug, VLX wallet stealthily converts hexadecimal address format(0x00000) to Velas address format(V000000). Please clarify if it is intended and change type hint for 'To:' field if it is.

**Comment by Corresponsible** [comment]
This is indeed the case, not a bug

**Comment by Ranger5789** [comment]
Not a bug then, and type hints is out of scope i assume.
