### ISSUE TITLE
[Android app] Wrong currency name in 'Fee:' field for some currencies

### ISSUE THREAD

**Issue by Ranger5789** [velas/mobile-wallet#25]
**Summary**
Wrong currency name in 'Fee:' field for some currencies(USDT, USDT_ERC20, SYX)

**Screenshot**
![Screenshot_2021-02-02-08-58-22-278](https://user-images.githubusercontent.com/10086309/106559717-dddfc080-6536-11eb-956f-b45b26fd9e55.jpeg)

**Steps to reproduce:**
1. Go to 'Wallets'
2. Tap on affected currency 
3. Tap 'Send'
4. Pay attention to 'Fee:' field

**Expected result**
Currency name of wallet currency

**Actual result**
BTC in USDT wallet
ETH in USDT_ERC20 wallet
VLX in SYX wallet

**Additional Screenshots and/or Videos**
![Screenshot_2021-02-02-08-57-56-376](https://user-images.githubusercontent.com/10086309/106559735-e637fb80-6536-11eb-8d5b-3db5d05f2a8f.jpeg)
![Screenshot_2021-02-02-08-57-17-202](https://user-images.githubusercontent.com/10086309/106559745-eb954600-6536-11eb-8116-f1854abe484e.jpeg)

**Environment:**
- Device: Lenovo TB-X606F
- OS: Android 10
- Version: Mobile wallet 1.1.0

**Comment by Corresponsible** [comment]
Paired currencies charge fee from parent currency

**Comment by Ranger5789** [comment]
Not a bug then, just awkward design.
