### ISSUE TITLE
[Android app] No information about date and fee in [History] after receiving BTC transactions

### ISSUE THREAD

**Issue by PrivetQA** [velas/mobile-wallet#27]
**Summary**
No information about date and fee in [History] after receiving BTC transactions

**Screenshot**
![image](https://user-images.githubusercontent.com/71498900/106583051-53ef2200-654d-11eb-885c-40b4ca816e01.png)

**Steps to reproduce:**
1. Receive BTC
2. Go to [History]
3. Pay attention to BTC transactions history

**Expected result**
Information(date, fee) about BTC transaction is displayed in [History] after receiving BTC transactions

**Actual result**
No information about date and fee in [History] after receiving BTC transactions

**Environment:**
 - Build [1.1.1]
 - OS [Android emulator]

**Comment by PrivetQA** [comment]
Environment:

Build [1.1.1]
OS [Android emulator]

**Comment by Corresponsible** [comment]
known but not listed, will give points and close
