### ISSUE TITLE
[Android app] Incorrect BTC fee after entering valid data 

### ISSUE THREAD

**Issue by PrivetQA** [velas/mobile-wallet#30]
**Summary**
Incorrect BTC fee after entering valid data 

**Screenshot**
![image](https://user-images.githubusercontent.com/71498900/106587854-cc0c1680-6552-11eb-8bb6-bdc0b8839a5e.png)

**Precondition**
BTC is added

**Steps to reproduce:**
1. Click on BTC wallet
2. Click on [SEND]
3. Enter valid address 
4. Enter valid amount
5. Pay attention to 'Fee' 

**Expected result**
[Send] is available, correct BTC fee is displayed

**Actual result**
Incorrect BTC fee after entering valid data 

**Environment:**
 - Build [1.1.1]
 - OS [Android emulator]

**Comment by PrivetQA** [comment]
Environment:

Build [1.1.1]
OS [Android emulator]

**Comment by PrivetQA** [comment]
Looks like its because fee of bitcoin network bigger than current balance, it is difficult for user to understand final commission

**Comment by Corresponsible** [comment]
Yes, fee bigger than balance is the case, re-file as incorrect fee
