### ISSUE TITLE
[Android app] Message 'Calc Fee Error' is shown after deleting 'Amount' values in USDT Omni sending page

### ISSUE THREAD

**Issue by PrivetQA** [velas/mobile-wallet#31]
**Summary**
Message 'Calc Fee Error' is shown after deleting 'Amount' values in USDT Omni sending page

**Screenshot**
![image](https://user-images.githubusercontent.com/71498900/106591803-60787800-6557-11eb-9e17-507e63df66d3.png)

**Steps to reproduce:**
1. Click on 'USDT Omni'
2. Click on [Send]
3. Click on 'Amount' field
4. Try to delete values

**Expected result**
No error message

**Actual result**
Message 'Calc Fee Error' is shown after deleting 'Amount' values in USDT Omni sending page

**Environment:**
 - Build [1.1.1]
 - OS [Android emulator]

**Comment by PrivetQA** [comment]
and others errors when try to enter invalid date into 'Amount' field
![image](https://user-images.githubusercontent.com/71498900/106592131-c9f88680-6557-11eb-9587-6901a6ba1264.png)

**Comment by PrivetQA** [comment]
Environment:

Build [1.1.1]
OS [Android emulator]

**Comment by Corresponsible** [comment]
Some currencies try to calculate fee from data they see in the fields immediately, this is due to currency peculiarities, maybe such behaviour will be handled later
