### ISSUE TITLE
[iOS app] The list of wallets isn’t saved after log out

### ISSUE THREAD

**Issue by irishad** [velas/mobile-wallet#43]
**Screenshot**
The main screen before log out https://drive.google.com/file/d/1oPi8VpomuZm8tlY_gS1wtoHgkNEvTKzS/view?usp=sharing
The main screen after restore https://drive.google.com/file/d/1eiXE1CqMZ-Qt5ZZyC-9MtsOBsWMmVYWB/view?usp=sharing

**Steps to reproduce:**
1.	Go to Wallets
2.	Add “Litecoin”
3.	Tap “Back”
4.	Go to Settings
5.	Tap "Log Out"
6.	Choose “New Account”
7.	Tap “Yes”
8.	Write Password
9.	Click "Enter"
10.	Tap "Restore"
11.	Enter seed phrase

**Expected result**
The list of wallets contains “Litecoin” at the main screen.

**Actual result**
The list of wallets doesn’t contain “Litecoin” at the main screen.

**Environment:**
 - Build [1.0.1]
 - OS [iOS 14.4]
 - Device [Iphone 7]

**Comment by Corresponsible** [comment]
After logout you will access your wallet in reset state, the wallets are there, but hidden, all you need to do is to add them back. Not a bug.
